"""Initial migrations

Revision ID: 383d4b90379e
Revises: d41094d03ea4
Create Date: 2024-06-29 22:08:44.483649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383d4b90379e'
down_revision = 'd41094d03ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_in_stock', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.alter_column('imageUrl',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('imageAlt',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_products_admin_id_admins'), 'admins', ['admin_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_products_category_id_categories'), 'categories', ['category_id'], ['id'])
        batch_op.drop_column('quantity')
        batch_op.drop_column('category')
        batch_op.drop_column('formattedPrice')
        batch_op.drop_column('numReviews')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numReviews', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('formattedPrice', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_products_category_id_categories'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_products_admin_id_admins'), type_='foreignkey')
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('imageAlt',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('imageUrl',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('admin_id')
        batch_op.drop_column('category_id')
        batch_op.drop_column('is_in_stock')

    # ### end Alembic commands ###
